
package com.newrelic.apm.enterprise.bmc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "execution_fault", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
public class ExecutionFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExecutionFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExecutionFault_Exception(String message, ExecutionFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExecutionFault_Exception(String message, ExecutionFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.newrelic.apm.enterprise.bmc.ExecutionFault
     */
    public ExecutionFault getFaultInfo() {
        return faultInfo;
    }

}
