
package com.newrelic.apm.enterprise.bmc;

import com.newrelic.apm.enterprise.Main;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImpactManager", targetNamespace = "http://imapi.bmc.com/2010/01", wsdlLocation = "file:///Users/plightbody/newrelic/webhook-processor/src/main/wsdl/bmc-impact-manager-7.3/ImpactManager.wsdl")
public class ImpactManager_Service
    extends Service
{

    private final static URL IMPACTMANAGER_WSDL_LOCATION;
    private final static WebServiceException IMPACTMANAGER_EXCEPTION;
    private final static QName IMPACTMANAGER_QNAME = new QName("http://imapi.bmc.com/2010/01", "ImpactManager");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = Main.class.getResource("/com/newrelic/apm/enterprise/bmc/ImpactManager.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        IMPACTMANAGER_WSDL_LOCATION = url;
        IMPACTMANAGER_EXCEPTION = e;
    }

    public ImpactManager_Service() {
        super(__getWsdlLocation(), IMPACTMANAGER_QNAME);
    }

    public ImpactManager_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMPACTMANAGER_QNAME, features);
    }

    public ImpactManager_Service(URL wsdlLocation) {
        super(wsdlLocation, IMPACTMANAGER_QNAME);
    }

    public ImpactManager_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMPACTMANAGER_QNAME, features);
    }

    public ImpactManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImpactManager_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImpactManager
     */
    @WebEndpoint(name = "ImpactManager")
    public ImpactManager getImpactManager() {
        return super.getPort(new QName("http://imapi.bmc.com/2010/01", "ImpactManager"), ImpactManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImpactManager
     */
    @WebEndpoint(name = "ImpactManager")
    public ImpactManager getImpactManager(WebServiceFeature... features) {
        return super.getPort(new QName("http://imapi.bmc.com/2010/01", "ImpactManager"), ImpactManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMPACTMANAGER_EXCEPTION!= null) {
            throw IMPACTMANAGER_EXCEPTION;
        }
        return IMPACTMANAGER_WSDL_LOCATION;
    }

}
