
package com.newrelic.apm.enterprise.bmc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImpactManager", targetNamespace = "http://imapi.bmc.com/2010/01")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImpactManager {


    /**
     * 
     * @param password
     * @param bufferType
     * @param userName
     * @param imname
     * @return
     *     returns long
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "Connect", action = "Connect")
    @WebResult(name = "connectionId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "Connect", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.Connect")
    @ResponseWrapper(localName = "Connect_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.ConnectOutput")
    public long connect(
        @WebParam(name = "userName", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String password,
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "bufferType", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        IMBufferType bufferType)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param deleteBuffer
     * @param connection
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "Disconnect", action = "Disconnect")
    @RequestWrapper(localName = "Disconnect", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.Disconnect")
    @ResponseWrapper(localName = "NoValue_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.NoValueOutput")
    public void disconnect(
        @WebParam(name = "connection", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        long connection,
        @WebParam(name = "deleteBuffer", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        boolean deleteBuffer)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param messageType
     * @param messageClass
     * @param connection
     * @param message
     * @param timeout
     * @return
     *     returns java.lang.String
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "SendEvent", action = "SendEvent")
    @WebResult(name = "response", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "SendEvent", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.SendEvent")
    @ResponseWrapper(localName = "SendEvent_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.SendEventOutput")
    public String sendEvent(
        @WebParam(name = "connection", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        long connection,
        @WebParam(name = "message", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        Event message,
        @WebParam(name = "timeout", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        int timeout,
        @WebParam(name = "messageClass", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String messageClass,
        @WebParam(name = "messageType", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        IMMessageType messageType)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param reliable
     * @param filterName
     * @param context
     * @param callbackURL
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "Subscribe", action = "Subscribe")
    @RequestWrapper(localName = "Subscribe", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.Subscribe")
    @ResponseWrapper(localName = "NoValue_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.NoValueOutput")
    public void subscribe(
        @WebParam(name = "filterName", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String filterName,
        @WebParam(name = "context", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String context,
        @WebParam(name = "callbackURL", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String callbackURL,
        @WebParam(name = "reliable", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        boolean reliable)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param filterName
     * @param context
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "Unsubscribe", action = "Unsubscribe")
    @RequestWrapper(localName = "Unsubscribe", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.Unsubscribe")
    @ResponseWrapper(localName = "NoValue_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.NoValueOutput")
    public void unsubscribe(
        @WebParam(name = "filterName", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String filterName,
        @WebParam(name = "context", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String context)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @return
     *     returns com.newrelic.apm.enterprise.bmc.ArrayOfCellInfo
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "GetCellInfo", action = "GetCellInfo")
    @WebResult(name = "CellInfo_Array", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "GetCellInfo", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.GetCellInfo")
    @ResponseWrapper(localName = "GetCellInfo_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.GetCellInfoOutput")
    public ArrayOfCellInfo getCellInfo()
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @return
     *     returns com.newrelic.apm.enterprise.bmc.ArrayOfString
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "GetFilterNames", action = "GetFilterNames")
    @WebResult(name = "StringArray", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "GetFilterNames", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.GetFilterNames")
    @ResponseWrapper(localName = "GetFilterNames_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.GetFilterNamesOutput")
    public ArrayOfString getFilterNames()
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param contextNio
     * @param filterName
     * @param numOfEvents
     * @return
     *     returns com.newrelic.apm.enterprise.bmc.GetEventsResponse
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "GetEvents", action = "GetEvents")
    @WebResult(name = "getEventsResponse", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "GetEvents", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.GetEvents")
    @ResponseWrapper(localName = "GetEvents_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.GetEventsOutput")
    public GetEventsResponse getEvents(
        @WebParam(name = "filterName", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String filterName,
        @WebParam(name = "context_nio", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String contextNio,
        @WebParam(name = "num_of_events", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        int numOfEvents)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param contextNio
     * @param filterName
     * @param numOfEvents
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "AckEvents", action = "AckEvents")
    @RequestWrapper(localName = "AckEvents", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.AckEvents")
    @ResponseWrapper(localName = "NoValue_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.NoValueOutput")
    public void ackEvents(
        @WebParam(name = "filterName", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String filterName,
        @WebParam(name = "context_nio", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String contextNio,
        @WebParam(name = "num_of_events", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        int numOfEvents)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultCount
     * @param resultHandle
     * @param query
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryEvents", action = "QueryEvents")
    @RequestWrapper(localName = "QueryEvents", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryEvents")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryEvents(
        @WebParam(name = "query", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String query,
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultCount
     * @param resultHandle
     * @param query
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryData", action = "QueryData")
    @RequestWrapper(localName = "QueryData", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryData")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryData(
        @WebParam(name = "query", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String query,
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param eventId
     * @param resultCount
     * @param resultHandle
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryEventByID", action = "QueryEventByID")
    @RequestWrapper(localName = "QueryEventByID", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryEventByID")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryEventByID(
        @WebParam(name = "eventId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String eventId,
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultCount
     * @param endDate
     * @param resultHandle
     * @param slotsList
     * @param classNames
     * @param startDate
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryEventsByDate", action = "QueryEventsByDate")
    @RequestWrapper(localName = "QueryEventsByDate", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryEventsByDate")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryEventsByDate(
        @WebParam(name = "startDate", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        XMLGregorianCalendar endDate,
        @WebParam(name = "classNames", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String classNames,
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "slotsList", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String slotsList,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultHandle
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "EndQuery", action = "EndQuery")
    @RequestWrapper(localName = "EndQuery", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.EndQuery")
    @ResponseWrapper(localName = "NoValue_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.NoValueOutput")
    public void endQuery(
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String resultHandle)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultHandle
     * @param timeout
     * @return
     *     returns long
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "GetQueryResultCount", action = "GetQueryResultCount")
    @WebResult(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "GetQueryResultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.GetQueryResultCount")
    @ResponseWrapper(localName = "GetQueryResultCount_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.GetQueryResultCountOutput")
    public long getQueryResultCount(
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String resultHandle,
        @WebParam(name = "timeout", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        int timeout)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param hStatus
     * @param resultCount
     * @param getSubclasses
     * @param resultHandle
     * @param slotsList
     * @param baseClass
     * @param lStatus
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryComponentsByStatus", action = "QueryComponentsByStatus")
    @RequestWrapper(localName = "QueryComponentsByStatus", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryComponentsByStatus")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryComponentsByStatus(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "lStatus", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String lStatus,
        @WebParam(name = "hStatus", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String hStatus,
        @WebParam(name = "baseClass", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String baseClass,
        @WebParam(name = "getSubclasses", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        boolean getSubclasses,
        @WebParam(name = "slotsList", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String slotsList,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param componentId
     * @param modeToSet
     * @param setOrCleared
     * @param comment
     * @param imname
     * @return
     *     returns java.lang.Integer
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "SetMaintenanceMode", action = "SetMaintenanceMode")
    @WebResult(name = "errorCode", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "SetMaintenanceMode", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.SetMaintenanceMode")
    @ResponseWrapper(localName = "SetMaintenanceMode_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.SetMaintenanceModeOutput")
    public Integer setMaintenanceMode(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "componentId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String componentId,
        @WebParam(name = "setOrCleared", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        Integer setOrCleared,
        @WebParam(name = "modeToSet", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String modeToSet,
        @WebParam(name = "comment", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String comment)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param componentId
     * @param componentStatus
     * @param comment
     * @param statusSet
     * @param imname
     * @return
     *     returns java.lang.Integer
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "SetManualStatus", action = "SetManualStatus")
    @WebResult(name = "errorCode", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "SetManualStatus", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.SetManualStatus")
    @ResponseWrapper(localName = "SetManualStatus_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.SetManualStatusOutput")
    public Integer setManualStatus(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "componentId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String componentId,
        @WebParam(name = "statusSet", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        Integer statusSet,
        @WebParam(name = "componentStatus", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String componentStatus,
        @WebParam(name = "comment", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String comment)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param condition
     * @param resultCount
     * @param resultHandle
     * @param slotsList
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryComponentsByCondition", action = "QueryComponentsByCondition")
    @RequestWrapper(localName = "QueryComponentsByCondition", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryComponentsByCondition")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryComponentsByCondition(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "condition", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String condition,
        @WebParam(name = "slotsList", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String slotsList,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultCount
     * @param componentId
     * @param resultHandle
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryComponentStatus", action = "QueryComponentStatus")
    @RequestWrapper(localName = "QueryComponentStatus", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryComponentStatus")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryComponentStatus(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "componentId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String componentId,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultCount
     * @param componentId
     * @param resultHandle
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryComponent", action = "QueryComponent")
    @RequestWrapper(localName = "QueryComponent", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryComponent")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryComponent(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "componentId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String componentId,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultCount
     * @param componentId
     * @param resultHandle
     * @param slotsList
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryModelImpact", action = "QueryModelImpact")
    @RequestWrapper(localName = "QueryModelImpact", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryModelImpact")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryModelImpact(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "componentId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String componentId,
        @WebParam(name = "slotsList", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String slotsList,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param resultCount
     * @param componentId
     * @param trueCause
     * @param resultHandle
     * @param slotsList
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryModelPossibleRootCauses", action = "QueryModelPossibleRootCauses")
    @RequestWrapper(localName = "QueryModelPossibleRootCauses", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryModelPossibleRootCauses")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryModelPossibleRootCauses(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "componentId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String componentId,
        @WebParam(name = "slotsList", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String slotsList,
        @WebParam(name = "trueCause", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        boolean trueCause,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param startIndex
     * @param retrieveResultHandle
     * @param numOfEvents
     * @param results
     * @param timeout
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "RetrieveQueryResults", action = "RetrieveQueryResults")
    @RequestWrapper(localName = "RetrieveQueryResults", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.RetrieveQueryResults")
    @ResponseWrapper(localName = "RetrieveQueryResults_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.RetrieveQueryResultsOutput")
    public void retrieveQueryResults(
        @WebParam(name = "retrieveResultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String retrieveResultHandle,
        @WebParam(name = "startIndex", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        long startIndex,
        @WebParam(name = "timeout", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        int timeout,
        @WebParam(name = "num_of_events", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.INOUT)
        Holder<Integer> numOfEvents,
        @WebParam(name = "results", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<TableOfNameValue> results)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param queryMode
     * @param baseClass
     * @param className
     * @param classOnly
     * @param imname
     * @return
     *     returns com.newrelic.apm.enterprise.bmc.ArrayOfClassDefInfo
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryClassDefinitions", action = "QueryClassDefinitions")
    @WebResult(name = "classDefs", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "QueryClassDefinitions", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryClassDefinitions")
    @ResponseWrapper(localName = "QueryClassDefinitions_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryClassDefinitionsOutput")
    public ArrayOfClassDefInfo queryClassDefinitions(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "queryMode", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        QueryMode queryMode,
        @WebParam(name = "baseClass", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String baseClass,
        @WebParam(name = "className", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String className,
        @WebParam(name = "classOnly", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        boolean classOnly)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param changeType
     * @param serverName
     * @param imname
     * @return
     *     returns java.lang.String
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "RegisterStateChange", action = "RegisterStateChange")
    @WebResult(name = "registrationID", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "RegisterStateChange", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.RegisterStateChange")
    @ResponseWrapper(localName = "RegisterStateChange_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.RegisterStateChangeOutput")
    public String registerStateChange(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "serverName", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String serverName,
        @WebParam(name = "changeType", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        StateChangeType changeType)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param registrationID
     * @param imname
     * @return
     *     returns int
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "UnregisterStateChange", action = "UnregisterStateChange")
    @WebResult(name = "resultCode", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
    @RequestWrapper(localName = "UnregisterStateChange", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.UnregisterStateChange")
    @ResponseWrapper(localName = "UnregisterStateChange_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.UnregisterStateChangeOutput")
    public int unregisterStateChange(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "registrationID", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String registrationID)
        throws ExecutionFault_Exception
    ;

    /**
     * 
     * @param onlyImpacted
     * @param resultCount
     * @param componentId
     * @param resultHandle
     * @param slotsList
     * @param imname
     * @throws ExecutionFault_Exception
     */
    @WebMethod(operationName = "QueryComponentEvents", action = "QueryComponentEvents")
    @RequestWrapper(localName = "QueryComponentEvents", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryComponentEvents")
    @ResponseWrapper(localName = "QueryResultHandle_output", targetNamespace = "http://blueprint.bmc.com/ImapiElems", className = "com.newrelic.apm.enterprise.bmc.QueryResultHandleOutput")
    public void queryComponentEvents(
        @WebParam(name = "imname", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String imname,
        @WebParam(name = "componentId", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String componentId,
        @WebParam(name = "slotsList", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        String slotsList,
        @WebParam(name = "onlyImpacted", targetNamespace = "http://blueprint.bmc.com/ImapiElems")
        boolean onlyImpacted,
        @WebParam(name = "resultHandle", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<String> resultHandle,
        @WebParam(name = "resultCount", targetNamespace = "http://blueprint.bmc.com/ImapiElems", mode = WebParam.Mode.OUT)
        Holder<Long> resultCount)
        throws ExecutionFault_Exception
    ;

}
